to_do_list/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from todo.views import index
from todo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('todo.urls')),
    # path('deleteURL',views.remove_task),
    

]

todo/urls.py
from django.conf.urls import url
from django.urls import path
from todo import views

app_name = "todo"

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^about',views.about, name='about'),
    url(r"^add_task/$",views.add_task,name = "add_task"),
    url(r'^deleteURL/(?P<task_id>[0-9]+)/$', views.remove_task, name='deleteURL'),
    path('deleteURL',views.remove_task),
    url(r'^modifyURL/(?P<task_id>[0-9]+)/$', views.modify_task, name='modifyURL'),
    path('modifyURL',views.modify_task),
    url(r"^modify_task/$",views.modify_task,name = "modify_task"),
    path('currentMonth',views.return_current_month),
    url(r'^calendarView/currentMonth$', views.return_current_month, name='currentMonth'),
    url(r'calendarView/$',views.calendar_view, name="calendar_view"),
]
    

todo/models.py
from django.db import models
from django.utils import timezone
 
 # Class to hold all the details of the task
class Task(models.Model):
    title = models.CharField(max_length = 75, unique=True)
    description = models.TextField(null=True)
    date = models.DateTimeField(default = timezone.now)
    deadline = models.DateTimeField(default= timezone.now)
 
    def __str__(self):
        return self.title
# Create your models here.

todo/forms.py
from todo.models import Task
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from django.forms.fields import DateTimeField
from todo.models import Task
from django.utils import timezone

class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=75, help_text="Enter the Title of Task")
    description = forms.CharField( widget=forms.Textarea, help_text="Enter the Description")
    date = DateTimeField(widget=forms.HiddenInput(), initial=timezone.now())
    deadline = DateTimeField(widget=forms.SelectDateWidget)
    
    class Meta:
        model = Task
        fields = ('title', 'description','deadline')

todo/views.py
from django.http import request
from django.shortcuts import redirect, render
from todo.models import Task
from todo.forms import TaskForm
from django.contrib import messages
from calendar import HTMLCalendar
import calendar

# Create your views here.
def index(request):
    task_list = Task.objects.order_by("deadline")
    context_dict = {'tasks' : task_list}
    return render(request,'todo/index.html', context_dict)

def about(request):
    context_dict = {}
    return render(request, 'todo/about.html',context_dict)

def add_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=True)
            return index(request) # direct user back to index page
            
        else:
            print(form.errors)
    
    context_dict = {'form' : form}
    return render(request,'todo/add_task.html',context_dict)

def remove_task(request):
    task_id = request.GET.get('DeleteButton')

    print('To be Deleted : ',task_id)
    item = Task.objects.get(title = task_id)
    print(item)
    item.delete()
    messages.info(request, "Item removed !!!")
    return index(request)

def modify_task(request):
    try:
        task_id = request.GET.get('ModifyButton')
        item = Task.objects.get(title = task_id)
        modified_task = item.title
        item.delete()
    except Task.DoesNotExist:
        modified_task = ''
        item = None

    
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    

    context_dict = {'form' : form, 'modified_task' : modified_task}
    return render(request, 'todo/modify_task.html', context_dict)



def calendar_view(request):
    task_list = Task.objects.order_by("deadline")
    current_year = task_list[0].deadline.year
    current_month = task_list[0].deadline.month
    cal = HTMLCalendar().formatmonth(current_year,current_month)


    month_str = task_list[0].deadline.strftime("%B") + ' ' + str(current_year)
    cal = cal.replace(month_str,'Fill',1)
    cal = cal.replace("0","2",1)
    cal = cal.replace("0","42",1)
    cal = cal.replace("0","99",1)

    # current_month = return_current_month(request) 

    for i in range(len(task_list)):
        # if task_list[i].deadline.month == current_month:
        date = str(task_list[i].deadline.date()).split('-')[2]
        replace_str = date + '<br/><strong>' + task_list[i].title + '</strong>'
        cal = cal.replace(date,replace_str,1)

    cal = cal.replace('Fill',month_str,1)

    context_dict = {'tasks' : task_list, 'cal':cal}

    return render(request, 'todo/calendar_view.html', context_dict)


#  Finish Function Definition
def return_current_month(request):
    task_list = Task.objects.order_by("deadline")
    current_month = task_list[0].deadline.month

    query_dict = dict(request.POST)
    
    prev_month = query_dict['PreviousMonth']
    print('Query Return Value : ',prev_month)
    print(query_dict.keys())

    return current_month

templates/todo/about.html
{% extends 'todo/base_bootstrap_index.html' %}
{% load static %}

{% block title %}
About v1.0
{% endblock %}

{% block body_block %}
</h3>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1>About</h1>
      <p>Coded by Kaustubh V in May 2021.</p>
      <p>This website was created to help users create a To-do List to manage their daily activities. The website uses Django and Sqlite as its backend and Bootstrap as its front end.
      </p>
      <p>Users can: </p>
      <li>Add a task with description and deadline</li>
      <li>Delete a task after completion</li>
      <li>Show Calendar View of Task with Closes Deadline</li>
      <p></p>
      <a href="mailto:kaustubhv@hotmail.com">Drop an Email!</a>
    </div>
  </div>
{% endblock %}

templates/todo/add_task.html
{% extends "todo/base_bootstrap_index.html" %}
{% block title %}Add Task{% endblock %}
{% block body_block %}
<form role="form" id="task_form" method="post" action="{% url 'todo:add_task' %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <br/>
    <br/>
    {% for field in form.visible_fields %}
        {{ field.errors }}
        <strong>{{ field.name }}</strong>
        {{ field }}
        <br/>
        <br/>

    {% endfor %}

    <button class="btn btn-primary" type="submit" name="submit">Create Task</button>
</div>	
</form>



{% endblock %}

templates/todo/base_bootstrap_index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>To Do List - {% block title %} Home {% endblock %}</title>
      <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'todo:index' %}">To Do List</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo:add_task' %}">Add Task</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo:calendar_view' %}">Calendar View</a>
          </li>


          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo:about' %}">About</a>
          </li>


        </ul>
        </div>
        </nav>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
          {% block body_block %}{% endblock %}
          </div>

        <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>

   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v5-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/todo/calendar_view.html
{% extends "todo/base_bootstrap_index.html" %}
{% load static %}
<!DOCTYPE html>
{% block title %}To Do List{% endblock %}
{% block body_block %}
{% if tasks %}
<br/>
{{ cal|safe }}
<!-- <form action = "currentMonth" method="POST">
  
<button type="submit" class = "btn btn-primary" name="PreviousMonth" value="{{ 1 }}">Previous Month</button>
<button type="submit" class = "btn btn-primary" name="NextMonth" value="{{ 1 }}">Next Month</button>
</form> -->
{% endif %}
{% endblock %}

templates/todo/index.html
{% extends "todo/base_bootstrap_index.html" %}
{% load static %}
<!DOCTYPE html>
{% block title %}To Do List{% endblock %}
{% block body_block %}
{% if tasks %}

<div class="container">
<table class="table">
    <thead>
      <tr>
        <th>Task</th>
        <th>Description</th>
        <th>Date Added</th>
        <th>Deadline</th>
      </tr>
    </thead>
    {% for task in tasks %}
    <tbody>
      <tr>
        <td>{{ task.title }}</td>
        <td>{{ task.description }}</td>
        <td> {{ task.date }}</td>
        <td> {{ task.deadline }}</td>
        <td>
          <form action = "deleteURL" method="GET">
            {% csrf_token %} 
          <button type="submit" class = "btn btn-danger" name="DeleteButton" value="{{ task.title }}">Delete</button>
        </form>
        <br/>
        <form action = "modifyURL" method="GET">
          {% csrf_token %} 
        <button type="submit" class = "btn btn-primary" name="ModifyButton" value="{{ task.title }}">Modify</button>
      </form>
        </td>
      </tr>      
        {% endfor %}
        {% else %}
        <br/>
    <h1><strong>No Tasks Added!</strong></h1>
    {% endif %}
    </tbody>
    </table>
    </div>
    {% endblock %}

templates/todo/modify_task.html
{% extends "todo/base_bootstrap_index.html" %}
{% block title %}Modify Task{% endblock %}
{% block body_block %}
<br/>
<h3>Modifying Task: {{ modified_task }}</h3>
<form role="form" id="task_form" method="post" action="{% url 'todo:modify_task' %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <br/>
    <br/>
    {% for field in form.visible_fields %}
        {{ field.errors }}
        <strong>{{ field.name }}</strong>
        {{ field }}
        <br/>
        <br/>

    {% endfor %}

    <button class="btn btn-primary" type="submit" name="submit">Modify Task</button>
</div>	
</form>



{% endblock %}